[package]
name = "day_8"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "bench"
harness = false

[dependencies]
num = "0.4.1"
